name: Netlify Deploy
on:
  workflow_run:
    workflows:
      - 'Build and Upload Artifacts'
    types:
      - completed
    branches:
      - deploy

jobs:
  deploy_heroes_service:
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          name: heroes-build-artifacts
          workflow: build-and-upload-artifacts.yml
          workflow_conclusion: success
          path: ./dist

      - name: Deploy Heroes Microapp Netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_HEROES_SITE_ID }}
        with:
          args: deploy --dir=./dist/apps/heroes --prod

      - name: Deploy Dashboard Microapp Netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_DASHBOARD_SITE_ID }}
        with:
          args: deploy --dir=./dist/apps/dashboard --prod

      - name: Deploy Main App Netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_MAIN_SITE_ID }}
        with:
          args: deploy --dir=./dist/apps/tour-of-heroes --prod
